//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema-lite";
import { type ModelResult as $ModelResult } from "@zenstackhq/orm";
export type Space = $ModelResult<$Schema, "Space">;
export type SpaceUser = $ModelResult<$Schema, "SpaceUser">;
export type User = $ModelResult<$Schema, "User">;
export type List = $ModelResult<$Schema, "List">;
export type Todo = $ModelResult<$Schema, "Todo">;
export type Account = $ModelResult<$Schema, "Account">;
export const SpaceUserRole = $schema.enums.SpaceUserRole.values;
export type SpaceUserRole = (typeof SpaceUserRole)[keyof typeof SpaceUserRole];
