//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        Space: {
            name: "Space",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                },
                owner: {
                    name: "owner",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("ownerId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "ownedSpaces", fields: ["ownerId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                ownerId: {
                    name: "ownerId",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]) }] }],
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]),
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                name: {
                    name: "name",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(4) }, { name: "max", value: ExpressionUtils.literal(50) }] }]
                },
                slug: {
                    name: "slug",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }, { name: "@regex", args: [{ name: "regex", value: ExpressionUtils.literal("^[0-9a-zA-Z]{4,16}$") }] }]
                },
                members: {
                    name: "members",
                    type: "SpaceUser",
                    array: true,
                    relation: { opposite: "space" }
                },
                lists: {
                    name: "lists",
                    type: "List",
                    array: true,
                    relation: { opposite: "space" }
                }
            },
            attributes: [
                { name: "@@deny", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.call("auth"), "==", ExpressionUtils._null()) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("create") }, { name: "condition", value: ExpressionUtils.literal(true) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("read") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.field("members"), "?", ExpressionUtils.binary(ExpressionUtils.field("user"), "==", ExpressionUtils.call("auth"))) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("update,delete") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.field("members"), "?", ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("user"), "==", ExpressionUtils.call("auth")), "&&", ExpressionUtils.binary(ExpressionUtils.field("role"), "==", ExpressionUtils.literal("ADMIN")))) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                slug: { type: "String" }
            }
        },
        SpaceUser: {
            name: "SpaceUser",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                },
                space: {
                    name: "space",
                    type: "Space",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("spaceId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "members", fields: ["spaceId"], references: ["id"], onDelete: "Cascade" }
                },
                spaceId: {
                    name: "spaceId",
                    type: "String",
                    foreignKeyFor: [
                        "space"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "memberships", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                role: {
                    name: "role",
                    type: "SpaceUserRole"
                }
            },
            attributes: [
                { name: "@@unique", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId"), ExpressionUtils.field("spaceId")]) }] },
                { name: "@@deny", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.call("auth"), "==", ExpressionUtils._null()) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("create") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.field("space"), ["owner"]), "==", ExpressionUtils.call("auth")) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("create") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.field("space"), ["members"]), "?", ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("user"), "==", ExpressionUtils.call("auth")), "&&", ExpressionUtils.binary(ExpressionUtils.field("role"), "==", ExpressionUtils.literal("ADMIN")))) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("update,delete") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.field("space"), ["members"]), "?", ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("user"), "==", ExpressionUtils.call("auth")), "&&", ExpressionUtils.binary(ExpressionUtils.field("role"), "==", ExpressionUtils.literal("ADMIN")))) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("read") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.field("space"), ["members"]), "?", ExpressionUtils.binary(ExpressionUtils.field("user"), "==", ExpressionUtils.call("auth"))) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                userId_spaceId: { userId: { type: "String" }, spaceId: { type: "String" } }
            }
        },
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true,
                    attributes: [{ name: "@unique" }, { name: "@email" }]
                },
                emailVerified: {
                    name: "emailVerified",
                    type: "DateTime",
                    optional: true
                },
                password: {
                    name: "password",
                    type: "String",
                    optional: true
                },
                name: {
                    name: "name",
                    type: "String",
                    optional: true
                },
                ownedSpaces: {
                    name: "ownedSpaces",
                    type: "Space",
                    array: true,
                    relation: { opposite: "owner" }
                },
                memberships: {
                    name: "memberships",
                    type: "SpaceUser",
                    array: true,
                    relation: { opposite: "user" }
                },
                image: {
                    name: "image",
                    type: "String",
                    optional: true,
                    attributes: [{ name: "@url" }]
                },
                lists: {
                    name: "lists",
                    type: "List",
                    array: true,
                    relation: { opposite: "owner" }
                },
                todos: {
                    name: "todos",
                    type: "Todo",
                    array: true,
                    relation: { opposite: "owner" }
                },
                accounts: {
                    name: "accounts",
                    type: "Account",
                    array: true,
                    relation: { opposite: "user" }
                }
            },
            attributes: [
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("read") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.call("auth"), "!=", ExpressionUtils._null()) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.call("auth"), "==", ExpressionUtils._this()) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        List: {
            name: "List",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                },
                space: {
                    name: "space",
                    type: "Space",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("spaceId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "lists", fields: ["spaceId"], references: ["id"], onDelete: "Cascade" }
                },
                spaceId: {
                    name: "spaceId",
                    type: "String",
                    foreignKeyFor: [
                        "space"
                    ]
                },
                owner: {
                    name: "owner",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("ownerId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "lists", fields: ["ownerId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                ownerId: {
                    name: "ownerId",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]) }] }],
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]),
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                title: {
                    name: "title",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(100) }] }]
                },
                private: {
                    name: "private",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                todos: {
                    name: "todos",
                    type: "Todo",
                    array: true,
                    relation: { opposite: "list" }
                }
            },
            attributes: [
                { name: "@@deny", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.call("auth"), "==", ExpressionUtils._null()) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("read") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("owner"), "==", ExpressionUtils.call("auth")), "||", ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.field("space"), ["members"]), "?", ExpressionUtils.binary(ExpressionUtils.field("user"), "==", ExpressionUtils.call("auth"))), "&&", ExpressionUtils.unary("!", ExpressionUtils.field("private")))) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("create") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("owner"), "==", ExpressionUtils.call("auth")), "&&", ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.field("space"), ["members"]), "?", ExpressionUtils.binary(ExpressionUtils.field("user"), "==", ExpressionUtils.call("auth")))) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("update,delete") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.field("owner"), "==", ExpressionUtils.call("auth")) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("update,delete") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.field("space"), ["members"]), "?", ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.field("user"), "==", ExpressionUtils.call("auth")), "&&", ExpressionUtils.binary(ExpressionUtils.field("role"), "==", ExpressionUtils.literal("ADMIN")))) }] },
                { name: "@@deny", args: [{ name: "operation", value: ExpressionUtils.literal("post-update") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.field("ownerId"), "!=", ExpressionUtils.member(ExpressionUtils.call("before"), ["ownerId"])) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Todo: {
            name: "Todo",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                },
                owner: {
                    name: "owner",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("ownerId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "todos", fields: ["ownerId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                ownerId: {
                    name: "ownerId",
                    type: "String",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]) }] }],
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]),
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                list: {
                    name: "list",
                    type: "List",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("listId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "todos", fields: ["listId"], references: ["id"], onDelete: "Cascade" }
                },
                listId: {
                    name: "listId",
                    type: "String",
                    foreignKeyFor: [
                        "list"
                    ]
                },
                title: {
                    name: "title",
                    type: "String",
                    attributes: [{ name: "@length", args: [{ name: "min", value: ExpressionUtils.literal(1) }, { name: "max", value: ExpressionUtils.literal(100) }] }]
                },
                completedAt: {
                    name: "completedAt",
                    type: "DateTime",
                    optional: true
                }
            },
            attributes: [
                { name: "@@deny", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.call("auth"), "==", ExpressionUtils._null()) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.field("list"), ["owner"]), "==", ExpressionUtils.call("auth")) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.field("list"), ["space", "members"]), "?", ExpressionUtils.binary(ExpressionUtils.field("user"), "==", ExpressionUtils.call("auth"))), "&&", ExpressionUtils.unary("!", ExpressionUtils.member(ExpressionUtils.field("list"), ["private"]))) }] },
                { name: "@@deny", args: [{ name: "operation", value: ExpressionUtils.literal("post-update") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.field("ownerId"), "!=", ExpressionUtils.member(ExpressionUtils.call("before"), ["ownerId"])) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Account: {
            name: "Account",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }],
                    default: ExpressionUtils.call("uuid")
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                type: {
                    name: "type",
                    type: "String"
                },
                provider: {
                    name: "provider",
                    type: "String"
                },
                providerAccountId: {
                    name: "providerAccountId",
                    type: "String"
                },
                refresh_token: {
                    name: "refresh_token",
                    type: "String",
                    optional: true
                },
                refresh_token_expires_in: {
                    name: "refresh_token_expires_in",
                    type: "Int",
                    optional: true
                },
                access_token: {
                    name: "access_token",
                    type: "String",
                    optional: true
                },
                expires_at: {
                    name: "expires_at",
                    type: "Int",
                    optional: true
                },
                token_type: {
                    name: "token_type",
                    type: "String",
                    optional: true
                },
                scope: {
                    name: "scope",
                    type: "String",
                    optional: true
                },
                id_token: {
                    name: "id_token",
                    type: "String",
                    optional: true
                },
                session_state: {
                    name: "session_state",
                    type: "String",
                    optional: true
                },
                user: {
                    name: "user",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }],
                    relation: { opposite: "accounts", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            attributes: [
                { name: "@@unique", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("provider"), ExpressionUtils.field("providerAccountId")]) }] }
            ],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                provider_providerAccountId: { provider: { type: "String" }, providerAccountId: { type: "String" } }
            }
        }
    } as const;
    enums = {
        SpaceUserRole: {
            name: "SpaceUserRole",
            values: {
                USER: "USER",
                ADMIN: "ADMIN"
            }
        }
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
