//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
export const schema = {
    provider: {
        type: "postgresql"
    },
    models: {
        Space: {
            name: "Space",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                owner: {
                    name: "owner",
                    type: "User",
                    relation: { opposite: "ownedSpaces", fields: ["ownerId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                ownerId: {
                    name: "ownerId",
                    type: "String",
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]),
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                name: {
                    name: "name",
                    type: "String"
                },
                slug: {
                    name: "slug",
                    type: "String",
                    unique: true
                },
                members: {
                    name: "members",
                    type: "SpaceUser",
                    array: true,
                    relation: { opposite: "space" }
                },
                lists: {
                    name: "lists",
                    type: "List",
                    array: true,
                    relation: { opposite: "space" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                slug: { type: "String" }
            }
        },
        SpaceUser: {
            name: "SpaceUser",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                space: {
                    name: "space",
                    type: "Space",
                    relation: { opposite: "members", fields: ["spaceId"], references: ["id"], onDelete: "Cascade" }
                },
                spaceId: {
                    name: "spaceId",
                    type: "String",
                    foreignKeyFor: [
                        "space"
                    ]
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "memberships", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                role: {
                    name: "role",
                    type: "SpaceUserRole"
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                userId_spaceId: { userId: { type: "String" }, spaceId: { type: "String" } }
            }
        },
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                email: {
                    name: "email",
                    type: "String",
                    unique: true
                },
                emailVerified: {
                    name: "emailVerified",
                    type: "DateTime",
                    optional: true
                },
                password: {
                    name: "password",
                    type: "String",
                    optional: true
                },
                name: {
                    name: "name",
                    type: "String",
                    optional: true
                },
                ownedSpaces: {
                    name: "ownedSpaces",
                    type: "Space",
                    array: true,
                    relation: { opposite: "owner" }
                },
                memberships: {
                    name: "memberships",
                    type: "SpaceUser",
                    array: true,
                    relation: { opposite: "user" }
                },
                image: {
                    name: "image",
                    type: "String",
                    optional: true
                },
                lists: {
                    name: "lists",
                    type: "List",
                    array: true,
                    relation: { opposite: "owner" }
                },
                todos: {
                    name: "todos",
                    type: "Todo",
                    array: true,
                    relation: { opposite: "owner" }
                },
                accounts: {
                    name: "accounts",
                    type: "Account",
                    array: true,
                    relation: { opposite: "user" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                email: { type: "String" }
            }
        },
        List: {
            name: "List",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                space: {
                    name: "space",
                    type: "Space",
                    relation: { opposite: "lists", fields: ["spaceId"], references: ["id"], onDelete: "Cascade" }
                },
                spaceId: {
                    name: "spaceId",
                    type: "String",
                    foreignKeyFor: [
                        "space"
                    ]
                },
                owner: {
                    name: "owner",
                    type: "User",
                    relation: { opposite: "lists", fields: ["ownerId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                ownerId: {
                    name: "ownerId",
                    type: "String",
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]),
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                title: {
                    name: "title",
                    type: "String"
                },
                private: {
                    name: "private",
                    type: "Boolean",
                    default: false
                },
                todos: {
                    name: "todos",
                    type: "Todo",
                    array: true,
                    relation: { opposite: "list" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Todo: {
            name: "Todo",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true
                },
                owner: {
                    name: "owner",
                    type: "User",
                    relation: { opposite: "todos", fields: ["ownerId"], references: ["id"], onDelete: "Cascade", hasDefault: true }
                },
                ownerId: {
                    name: "ownerId",
                    type: "String",
                    default: ExpressionUtils.member(ExpressionUtils.call("auth"), ["id"]),
                    foreignKeyFor: [
                        "owner"
                    ]
                },
                list: {
                    name: "list",
                    type: "List",
                    relation: { opposite: "todos", fields: ["listId"], references: ["id"], onDelete: "Cascade" }
                },
                listId: {
                    name: "listId",
                    type: "String",
                    foreignKeyFor: [
                        "list"
                    ]
                },
                title: {
                    name: "title",
                    type: "String"
                },
                completedAt: {
                    name: "completedAt",
                    type: "DateTime",
                    optional: true
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Account: {
            name: "Account",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    default: ExpressionUtils.call("uuid")
                },
                userId: {
                    name: "userId",
                    type: "String",
                    foreignKeyFor: [
                        "user"
                    ]
                },
                type: {
                    name: "type",
                    type: "String"
                },
                provider: {
                    name: "provider",
                    type: "String"
                },
                providerAccountId: {
                    name: "providerAccountId",
                    type: "String"
                },
                refresh_token: {
                    name: "refresh_token",
                    type: "String",
                    optional: true
                },
                refresh_token_expires_in: {
                    name: "refresh_token_expires_in",
                    type: "Int",
                    optional: true
                },
                access_token: {
                    name: "access_token",
                    type: "String",
                    optional: true
                },
                expires_at: {
                    name: "expires_at",
                    type: "Int",
                    optional: true
                },
                token_type: {
                    name: "token_type",
                    type: "String",
                    optional: true
                },
                scope: {
                    name: "scope",
                    type: "String",
                    optional: true
                },
                id_token: {
                    name: "id_token",
                    type: "String",
                    optional: true
                },
                session_state: {
                    name: "session_state",
                    type: "String",
                    optional: true
                },
                user: {
                    name: "user",
                    type: "User",
                    relation: { opposite: "accounts", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" },
                provider_providerAccountId: { provider: { type: "String" }, providerAccountId: { type: "String" } }
            }
        }
    },
    enums: {
        SpaceUserRole: {
            USER: "USER",
            ADMIN: "ADMIN"
        }
    },
    authType: "User",
    plugins: {}
} as const satisfies SchemaDef;
export type SchemaType = typeof schema;
